### ISSUE TITLE
Error when you Click on "watch" button

### ISSUE THREAD

**Issue by Sudhanshu-Bharti** [atoms19/anilook#1]
Seems like there is some issue while handeling the event. Can you please check ?
![image](https://github.com/atoms19/anilook/assets/120251980/84fb8f07-763b-4499-ae4b-062cf7dd0ab7)

**Comment by atoms19** [comment]
ooh event problem ic , I'll check  thanks for pointing out 😊

**Comment by atoms19** [comment]
for some reason api isnt returning episode links for most animes 🥹 , hope they'll fix the api soon 
 else I'll have to switch my api to anify or that zoro api 
which is a lot of work 🌊🐃 

thinking of rewriting this thing in svelte with tailwind soon but rn i am stuck in the middle of lots of exams 💀 
hopefully when this jee madness settles I'll fix it👍

**Comment by Sudhanshu-Bharti** [comment]
> for some reason api isnt returning episode links for most animes 🥹 , hope they'll fix the api soon 
>  else I'll have to switch my api to anify or that zoro api 
> which is a lot of work 🌊🐃 
> 
> thinking of rewriting this thing in svelte with tailwind soon but rn i am stuck in the middle of lots of exams 💀 
> hopefully when this jee madness settles I'll fix it👍

Ya thats true . It has constant issues. You may also try this api: https://github.com/ghoshRitesh12/aniwatch-api

Its aniwatch api but has some limiter enabled. I would suggest you to clone and host it on your own.


Btw i was also an jee aspirant lol. Jee such a pain. All the best

 do you use nextjs or react? I was looking for a collaborative project :)

**Comment by atoms19** [comment]
i have tried that api before i thought of not using it due to its performance but
  ic  hosting my own instance might improve its speed 

thanks dude ✌️ I'll be ready for a collab after the exams hopefully, my nextjs skills aint gud enough yet

**Comment by Sudhanshu-Bharti** [comment]
> i have tried that api before i thought of not using it due to its performance but
>   ic  hosting my own instance might improve its speed 
> 
> thanks dude ✌️ I'll be ready for a collab after the exams hopefully, my nextjs skills aint gud enough yet

Yeah sure, will do after your exams and my midsem exams. XD

**Comment by atoms19** [comment]
bro , i fixed the issue 👍, my fork of the api wasnt up-to-date that was the problem, now fixed : )
